Repository sendgrid/csharp-http-client, pull requests merged in 2019-08, with the labels that each got.

#85 Fix test looking for LICENSE.txt
  UnitTest/UnitTest.cs
Labels: difficulty: easy, status: code review request, status: hacktoberfest approved

#84 Update README.md
  README.md
Labels: difficulty: easy, status: code review request, status: hacktoberfest approved

#83 Fixed broken feature request link
  README.md
Labels: difficulty: easy, status: code review request, status: hacktoberfest approved

#78 Document new Git workflow
  .github/PULL_REQUEST_TEMPLATE
  CONTRIBUTING.md
Labels: difficulty: easy, good first issue, hacktoberfest, status: code review request, status: hacktoberfest approved, type: docs update

#74 Add first-timers.md file for newcomers
  FIRST_TIMERS.md
  static/img/github-fork.png
  static/img/github-signup.png
Labels: difficulty: medium, hacktoberfest, status: code review request, status: hacktoberfest approved, type: docs update

#70 Corrected *.md files using Grammarly
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: difficulty: medium, hacktoberfest, status: code review request, status: hacktoberfest approved, type: docs update

#62 Added CodeCov support
  .travis.yml
Labels: difficulty: easy, status: code review request, type: sendgrid enhancement

#60 Add Code Review to Contributing.md #59
  CONTRIBUTING.md
Labels: difficulty: easy, status: code review request, type: docs update

#90 Twilio branding updates
  .github/PULL_REQUEST_TEMPLATE
  .gitignore
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  CSharpHTTPClient/Properties/AssemblyInfo.cs
  Example/Example.cs
  FIRST_TIMERS.md
  LICENSE.md
  README.md
  TROUBLESHOOTING.md
Labels: status: code review request
